### ISSUE TITLE
Improve user approbation workflow

### ISSUE THREAD

**Issue by Thrainsa** [alakajam-team/alakajam#542] opened 2020-06-16 14:36 UTC
For now a user can register itself has a streamer for an event and if the rating phase start he can vote.
If the user is banned, the ratings will still counts.

We should remove it's rating in case of ban (same issue for multi-account)

**Comment by mkalam-alami** [comment] 2020-06-16 15:11
In general we don't have real tools for moderating ratings. Ideally we would have:

- A special event tab for disabling the ratings of a specific user.
- Maybe a way to detect users making strange ratings (eg. too low/too fast), because I would prefer if even mods cannot see individual ratings of regular users.

**Comment by mkalam-alami** [comment] 2020-11-01 14:07
Closing this one as it's a duplicate of #308 in the end

**Closed by mkalam-alami** 2020-11-01 14:07 UTC
