### ISSUE TITLE
Styling issue on comments sidebar

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#503] opened 2020-02-23 19:20 UTC
![Clipboard02](https://user-images.githubusercontent.com/694508/75118385-ff270400-5679-11ea-9628-b393317b1c07.jpg)

**Comment by coxm** [comment] 2021-02-01 22:19
I suspect this is a duplicate of https://github.com/alakajam-team/alakajam/issues/554. I'll close for now, but obviously we'll re-open if persists.

**Closed by coxm** 2021-02-01 22:19 UTC
Labels: bug
